"""Industrial-grade domain schemas for the Agentic RAG system.

All scores are validated via ``validate_score`` — bool, NaN, inf, and
out-of-range values are rejected at construction time.

Every schema supports ``to_dict()`` / ``from_dict()`` for serialisation.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any

from career_agent.domain.validation import validate_score

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _uid(prefix: str = "") -> str:
    return f"{prefix}{uuid.uuid4().hex[:12]}"


# ---------------------------------------------------------------------------
# ParsedJD
# ---------------------------------------------------------------------------


@dataclass
class ParsedJD:
    """Structured representation of a parsed job description."""

    job_title: str = ""
    job_direction: str = "general"
    hard_skills: list[str] = field(default_factory=list)
    bonus_skills: list[str] = field(default_factory=list)
    soft_skills: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)
    raw_text: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "job_title": self.job_title,
            "job_direction": self.job_direction,
            "hard_skills": list(self.hard_skills),
            "bonus_skills": list(self.bonus_skills),
            "soft_skills": list(self.soft_skills),
            "keywords": list(self.keywords),
            "raw_text": self.raw_text,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ParsedJD:
        return cls(
            job_title=str(d.get("job_title", "")),
            job_direction=str(d.get("job_direction", "general")),
            hard_skills=list(d.get("hard_skills", [])),
            bonus_skills=list(d.get("bonus_skills", [])),
            soft_skills=list(d.get("soft_skills", [])),
            keywords=list(d.get("keywords", [])),
            raw_text=str(d.get("raw_text", "")),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# RetrievalQuery
# ---------------------------------------------------------------------------


@dataclass
class RetrievalQuery:
    """A retrieval query generated by the planner or rewrite node."""

    query_text: str = ""
    query_id: str = field(default_factory=lambda: _uid("qry_"))
    round: int = 1
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "query_id": self.query_id,
            "query_text": self.query_text,
            "round": self.round,
            "reason": self.reason,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> RetrievalQuery:
        return cls(
            query_id=str(d.get("query_id", _uid("qry_"))),
            query_text=str(d.get("query_text", "")),
            round=int(d.get("round", 1)),
            reason=str(d.get("reason", "")),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# DocumentChunk (domain version — aligns with rag.schemas.DocumentChunk)
# ---------------------------------------------------------------------------


@dataclass
class DocumentChunk:
    """A text chunk from a source document, ready for indexing."""

    chunk_id: str = field(default_factory=lambda: _uid("chk_"))
    document_id: str = ""
    content: str = ""
    source_path: str = ""
    chunk_index: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "document_id": self.document_id,
            "content": self.content,
            "source_path": self.source_path,
            "chunk_index": self.chunk_index,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> DocumentChunk:
        return cls(
            chunk_id=str(d.get("chunk_id", _uid("chk_"))),
            document_id=str(d.get("document_id", "")),
            content=str(d.get("content", "")),
            source_path=str(d.get("source_path", "")),
            chunk_index=int(d.get("chunk_index", 0)),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# RetrievedChunk
# ---------------------------------------------------------------------------


@dataclass
class RetrievedChunk:
    """A chunk returned by hybrid retrieval with per-signal scores."""

    chunk_id: str
    source: str
    content: str
    summary: str = ""
    keyword_score: float = 0.0
    vector_score: float = 0.0
    metadata_score: float = 0.0
    final_hybrid_score: float = 0.0
    rerank_score: float = 0.0
    matched_skills: list[str] = field(default_factory=list)
    rerank_reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.keyword_score = validate_score(self.keyword_score, "keyword_score")
        self.vector_score = validate_score(self.vector_score, "vector_score")
        self.metadata_score = validate_score(self.metadata_score, "metadata_score")
        self.final_hybrid_score = validate_score(
            self.final_hybrid_score, "final_hybrid_score"
        )
        self.rerank_score = validate_score(self.rerank_score, "rerank_score")

    def to_dict(self) -> dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "source": self.source,
            "content": self.content,
            "summary": self.summary,
            "keyword_score": self.keyword_score,
            "vector_score": self.vector_score,
            "metadata_score": self.metadata_score,
            "final_hybrid_score": self.final_hybrid_score,
            "rerank_score": self.rerank_score,
            "matched_skills": list(self.matched_skills),
            "rerank_reason": self.rerank_reason,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> RetrievedChunk:
        return cls(
            chunk_id=str(d.get("chunk_id", "")),
            source=str(d.get("source", "")),
            content=str(d.get("content", "")),
            summary=str(d.get("summary", "")),
            keyword_score=float(d.get("keyword_score", 0.0)),
            vector_score=float(d.get("vector_score", 0.0)),
            metadata_score=float(d.get("metadata_score", 0.0)),
            final_hybrid_score=float(d.get("final_hybrid_score", 0.0)),
            rerank_score=float(d.get("rerank_score", 0.0)),
            matched_skills=list(d.get("matched_skills", [])),
            rerank_reason=str(d.get("rerank_reason", "")),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# RetrievalScore
# ---------------------------------------------------------------------------


@dataclass
class RetrievalScore:
    """Aggregated retrieval quality score — aligns with RetrievalGradeReport."""

    total_score: float = 0.0
    grade: str = "failed"
    query: str = ""
    top_k: int = 5
    evidence_count: int = 0
    average_score: float = 0.0
    keyword_coverage: float = 0.0
    source_diversity: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.total_score = validate_score(self.total_score, "total_score")
        self.average_score = validate_score(self.average_score, "average_score")
        self.keyword_coverage = validate_score(
            self.keyword_coverage, "keyword_coverage"
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_score": self.total_score,
            "grade": self.grade,
            "query": self.query,
            "top_k": self.top_k,
            "evidence_count": self.evidence_count,
            "average_score": self.average_score,
            "keyword_coverage": self.keyword_coverage,
            "source_diversity": self.source_diversity,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> RetrievalScore:
        return cls(
            total_score=float(d.get("total_score", 0.0)),
            grade=str(d.get("grade", "failed")),
            query=str(d.get("query", "")),
            top_k=int(d.get("top_k", 5)),
            evidence_count=int(d.get("evidence_count", 0)),
            average_score=float(d.get("average_score", 0.0)),
            keyword_coverage=float(d.get("keyword_coverage", 0.0)),
            source_diversity=int(d.get("source_diversity", 0)),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# Evidence
# ---------------------------------------------------------------------------


@dataclass
class Evidence:
    """A piece of evidence selected to support a generated claim."""

    evidence_id: str = field(default_factory=lambda: _uid("ev_"))
    chunk_id: str = ""
    source: str = ""
    content: str = ""
    supported_claims: list[str] = field(default_factory=list)
    confidence: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.confidence = validate_score(self.confidence, "confidence")

    def to_dict(self) -> dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "chunk_id": self.chunk_id,
            "source": self.source,
            "content": self.content,
            "supported_claims": list(self.supported_claims),
            "confidence": self.confidence,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Evidence:
        return cls(
            evidence_id=str(d.get("evidence_id", _uid("ev_"))),
            chunk_id=str(d.get("chunk_id", "")),
            source=str(d.get("source", "")),
            content=str(d.get("content", "")),
            supported_claims=list(d.get("supported_claims", [])),
            confidence=float(d.get("confidence", 0.0)),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# MatchAnalysis
# ---------------------------------------------------------------------------


@dataclass
class MatchAnalysis:
    """Result of matching JD requirements against retrieved evidence."""

    strengths: list[str] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)
    matched_skills: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "strengths": list(self.strengths),
            "weaknesses": list(self.weaknesses),
            "recommendations": list(self.recommendations),
            "matched_skills": list(self.matched_skills),
            "suggestions": list(self.suggestions),
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> MatchAnalysis:
        return cls(
            strengths=list(d.get("strengths", [])),
            weaknesses=list(d.get("weaknesses", [])),
            recommendations=list(d.get("recommendations", [])),
            matched_skills=list(d.get("matched_skills", [])),
            suggestions=list(d.get("suggestions", [])),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# GeneratedBullet
# ---------------------------------------------------------------------------


@dataclass
class GeneratedBullet:
    """A single generated resume bullet with mandatory source grounding."""

    text: str = ""
    evidence_ids: list[str] = field(default_factory=list)
    source_paths: list[str] = field(default_factory=list)
    confidence: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.confidence = validate_score(self.confidence, "confidence")

    @property
    def has_evidence(self) -> bool:
        """True if this bullet is grounded in at least one evidence or source."""
        return bool(self.evidence_ids or self.source_paths)

    def to_dict(self) -> dict[str, Any]:
        return {
            "text": self.text,
            "evidence_ids": list(self.evidence_ids),
            "source_paths": list(self.source_paths),
            "confidence": self.confidence,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> GeneratedBullet:
        return cls(
            text=str(d.get("text", "")),
            evidence_ids=list(d.get("evidence_ids", [])),
            source_paths=list(d.get("source_paths", [])),
            confidence=float(d.get("confidence", 0.0)),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# AgentDecision
# ---------------------------------------------------------------------------


_DECISION_NEXT_ACTION: dict[str, str] = {
    "continue": "analyze_match",
    "retry": "rewrite_query",
    "fallback": "end",
}


@dataclass
class AgentDecision:
    """A structured decision made by the agent planner."""

    decision: str = "continue"
    reason: str = ""
    next_action: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.next_action:
            self.next_action = _DECISION_NEXT_ACTION.get(
                self.decision, "analyze_match"
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "decision": self.decision,
            "reason": self.reason,
            "next_action": self.next_action,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> AgentDecision:
        return cls(
            decision=str(d.get("decision", "continue")),
            reason=str(d.get("reason", "")),
            next_action=str(d.get("next_action", "")),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# ToolCallTrace
# ---------------------------------------------------------------------------


@dataclass
class ToolCallTrace:
    """A single tool invocation record."""

    tool_name: str = ""
    input_summary: str = ""
    output_summary: str = ""
    duration_ms: float = 0.0
    success: bool = False
    error: str = ""
    state_changes: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool_name": self.tool_name,
            "input_summary": self.input_summary,
            "output_summary": self.output_summary,
            "duration_ms": self.duration_ms,
            "success": self.success,
            "error": self.error,
            "state_changes": list(self.state_changes),
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ToolCallTrace:
        return cls(
            tool_name=str(d.get("tool_name", "")),
            input_summary=str(d.get("input_summary", "")),
            output_summary=str(d.get("output_summary", "")),
            duration_ms=float(d.get("duration_ms", 0.0)),
            success=bool(d.get("success", False)),
            error=str(d.get("error", "")),
            state_changes=list(d.get("state_changes", [])),
            metadata=dict(d.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# WorkflowTrace
# ---------------------------------------------------------------------------


@dataclass
class WorkflowTrace:
    """Aggregated trace of an entire workflow run."""

    trace_id: str = field(default_factory=lambda: _uid("trace_"))
    tool_traces: list[ToolCallTrace] = field(default_factory=list)
    final_decision: str = ""
    total_duration_ms: float = 0.0
    status: str = "running"
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.total_duration_ms and self.tool_traces:
            self.total_duration_ms = sum(
                t.duration_ms for t in self.tool_traces
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "trace_id": self.trace_id,
            "tool_traces": [t.to_dict() for t in self.tool_traces],
            "final_decision": self.final_decision,
            "total_duration_ms": self.total_duration_ms,
            "status": self.status,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> WorkflowTrace:
        traces = [
            ToolCallTrace.from_dict(t)
            for t in d.get("tool_traces", [])
        ]
        return cls(
            trace_id=str(d.get("trace_id", _uid("trace_"))),
            tool_traces=traces,
            final_decision=str(d.get("final_decision", "")),
            total_duration_ms=float(d.get("total_duration_ms", 0.0)),
            status=str(d.get("status", "running")),
            metadata=dict(d.get("metadata", {})),
        )
