"""PDF resume exporter — generates professional PDF resumes."""

from __future__ import annotations
from pathlib import Path
from typing import Any


def export_pdf(
    output_path: str,
    profile_info: dict[str, Any] | None = None,
    match_result: dict[str, Any] | None = None,
    generated_bullets: list[str] | None = None,
    template: str = "agent_role",
) -> str:
    """Export a PDF resume. Returns the absolute path."""
    from fpdf import FPDF

    info = profile_info or {}
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Register CJK font for Chinese support
    font_dir = "/usr/share/fonts/opentype/noto"
    try:
        pdf.add_font("NotoSans", "", f"{font_dir}/NotoSansCJK-Regular.ttc", uni=True)
        pdf.add_font("NotoSans", "B", f"{font_dir}/NotoSansCJK-Bold.ttc", uni=True)
        use_font = "NotoSans"
    except Exception:
        use_font = "Helvetica"

    # Title
    pdf.set_font(use_font, "B", 18)
    pdf.cell(0, 10, info.get("name", "姓名"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Contact
    pdf.set_font(use_font, "", 10)
    contact_parts = []
    for key in ["school", "major", "email", "phone", "github"]:
        if info.get(key):
            contact_parts.append(str(info[key]))
    pdf.cell(0, 6, " | ".join(contact_parts), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Education
    if info.get("school"):
        pdf.set_font(use_font, "B", 13)
        pdf.cell(0, 8, "教育背景", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(use_font, "", 11)
        edu = f"{info.get('school', '')} | {info.get('major', '')}"
        if info.get("degree"):
            edu += f" | {info['degree']}"
        pdf.cell(0, 7, edu, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # Skills
    if match_result:
        matched = match_result.get("matched_skills", [])
        if matched:
            pdf.set_font(use_font, "B", 13)
            pdf.cell(0, 8, "专业技能", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font(use_font, "", 10)
            pdf.multi_cell(0, 6, ", ".join(matched[:15]))
            pdf.ln(3)

    # Projects
    bullets = generated_bullets or []
    if bullets:
        pdf.set_font(use_font, "B", 13)
        pdf.cell(0, 8, "项目经历", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(use_font, "", 10)
        for bullet in bullets[:5]:
            text = bullet.replace("# ", "").replace("\n", " ")[:200]
            if text.startswith("- "):
                text = text[2:]
            pdf.set_x(15)
            pdf.cell(5, 6, chr(8226))  # bullet point
            pdf.multi_cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # Self eval
    if match_result:
        strengths = match_result.get("matched_skills", [])
        if strengths:
            pdf.set_font(use_font, "B", 13)
            pdf.cell(0, 8, "自我评价", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font(use_font, "", 10)
            pdf.multi_cell(0, 6, f"具备 {', '.join(strengths[:6])} 等方面的项目经验和实践能力。")
            pdf.ln(3)

    # Footer
    pdf.set_font(use_font, "", 8)
    pdf.cell(0, 6, "Generated by Smart Apply Agent | Evidence-grounded resume", align="C")

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(path))
    return str(path.resolve())
